=== angeligareta/XML-Project/src/xsd/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.practicasipc.edu"
           xmlns="http://www.practicasipc.edu">

    <!-- La herramienta usada para comprobar que el documento es válido es el IDE Netbeans -->

    <!-- Ejemplo muy util de XSD https://stackoverflow.com/questions/14269541/xsd-restriction-on-attribute -->


<!--~~~ Definición de tipos simpleType para los atributos con dominio restringido. ~~~-->

    <!-- Definición del tipo difficulty -->
    <xs:simpleType name="difficultyType">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="fácil" />
            <xs:enumeration value="media" />
            <xs:enumeration value="difícil" />
        </xs:restriction>
    </xs:simpleType> 
    
    <!-- Definición del tipo course -->
    <xs:simpleType name="courseType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="primero" />
            <xs:enumeration value="segundo" />
            <xs:enumeration value="postre" />
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Definición del tipo unit -->
    <xs:simpleType name="unitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="l"  />
            <xs:enumeration value="cl" />
            <xs:enumeration value="ml" />
            <xs:enumeration value="kg" />
            <xs:enumeration value="gr"  />
            <xs:enumeration value="mg" />
            <xs:enumeration value="unidad" />
            <xs:enumeration value="unidades" />
            <xs:enumeration value="cucharadita" />
        </xs:restriction>
    </xs:simpleType>
    
    
<!--~~~ Definición de tipos complexType para elementos ~~~-->
    
    <!-- Definición del tipo foto -->
    <xs:complexType name="PhotoType">
        <xs:attribute name="src" type="xs:anyURI" use="required"/>
        <xs:attribute name="alt" type="xs:string" use="required"/>
    </xs:complexType>
    
    <!-- Definición del tipo ingrediente -->
    <xs:complexType name="IngredientType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="quantity" type="xs:double" use="required"/>
        <xs:attribute name="unit" type="unitType" use="required"/>
    </xs:complexType>
    
    <!-- Definición del tipo lista de ingredientes -->
    <xs:complexType name="IngredientListType">
        <xs:sequence>
            <xs:element name="ingredient" type="IngredientType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Definición del tipo paso(step) -->
    <!-- 
        Estos elementos extras anidados son necesarios
        para poder poner texto dentro de los elementos de este tipo
     -->
    <xs:complexType name="InstructionType">
        <xs:simpleContent>
          <xs:extension base="xs:string">
            <xs:attribute name="number" type="xs:integer" use="required"/>
          </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <!-- Definición del tipo instrucciones -->
    <xs:complexType name="InstructionListType">
        <xs:sequence>
            <xs:element name="instruction" type="InstructionType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Definición del tipo receta -->
    <xs:complexType name="RecipeType">
        <!-- Elementos. Primero tienen que ir los elementos y luego los attributos -->
        <xs:sequence>
            <xs:element name="photo" type="PhotoType"/>
            <xs:element name="ingredient-list" type="IngredientListType"/>
            <xs:element name="instruction-list" type="InstructionListType"/>
        </xs:sequence>
        
        <!-- Atributos -->
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="author" type="xs:string"/>
        <xs:attribute name="duration" type="xs:integer" use="required"/> <!-- Las unidades son siempre segundos -->
        <xs:attribute name="difficulty" type="difficultyType" use="required"/> <!-- Restricción cadenas específicas.-->
        <xs:attribute name="number-of-people" type="xs:integer" use="required"/>
        <xs:attribute name="course" type="courseType" use="required"/>
    </xs:complexType>
    
    
    <!--~~~ Definición del libro de recetas ~~~-->
    <xs:element name="recipe-book">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recipe" minOccurs="1" maxOccurs="unbounded" type="RecipeType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== angeligareta/XML-Project/XML/recipe-book.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="../XSL/recipe-book.xsl"?>

<!--
    Hemos usado el IDE Netbeans para la validación. Para ello
    creamos un proyecto de HTML (creo que vale cualquiera) y 
    creamos el fichero XML a validar y el XSD. Y para validar
    usando ese XSD local seguimos los pasos en:
    https://stackoverflow.com/questions/3579413/netbeans-how-to-provide-offline-xml-schemas
    
    1. Select the 'DTDs and XML Schemas' item from the Tools menu.
    A dialog box will open.

    2. Scroll through the list on the left until the item 'User catalog [read-write] is visible.
    Select that item.

    3. Press the button titled 'Add Local DTD or Schema...'
-->

<!-- Libro de recetas -->
<recipe-book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.practicasipc.edu"
             xsi:schemaLocation="http://www.practicasipc.edu ../XSD/schema.xsd">
    <!-- Course significa tipo de plato (primero, segundo o postre)-->
    <!-- Las unidades de "duration" son segundos -->
    <recipe name="Tarta de gofio y bienmesabe" author="Ángel" duration="5400" difficulty="difícil" number-of-people="6" course="postre">
        
        <!-- Foto principal de cada receta -->
        <photo src="https://img-global.cpcdn.com/002_recipes/9386e4aca812db89/640x640sq70/photo.jpg" alt="Imagen del resultado" />

        <!-- Lista de ingredientes para cada receta -->
        <ingredient-list>
            <ingredient name="Gofio" quantity="600" unit="gr" />
            <ingredient name="Levadura" quantity="17" unit="gr" />
            <ingredient name="Bicarbonato" quantity="0.25" unit="cucharadita" />
            <ingredient name="Huevos M" quantity="3" unit="unidades" />
            <ingredient name="Azúcar" quantity="500" unit="gr" />
            <ingredient name="Aceite de girasol" quantity="300" unit="ml" />
            <ingredient name="Leche semidesnatada" quantity="360" unit="ml" />
            <ingredient name="Nata vegetal" quantity="250" unit="ml" />
            <ingredient name="Esencia de vainilla" quantity="1" unit="unidad" />
            <ingredient name="Bienmesabe" quantity="1" unit="unidad" />
            <ingredient name="Dulce de leche" quantity="100" unit="ml" />
        </ingredient-list>

        <!-- Lista de instrucciones para cada receta -->
        <instruction-list>
            <instruction number="2">
                Ahora bajamos la velocidad de la batidora 
                y tamizamos sobre nuestra mezcla la 
                harina el gofio la sal la levadura y el bicarbonato.
                Integramos con la pala de la batidora.
            </instruction>
            <instruction number="1">
                Comenzamos preparando el bizcocho para ello
                blanqueamos en la batidora los huevos junto con el azúcar,
                seguidamente añadimos el aceite y la leche.
            </instruction>
            <instruction number="3">
                Engrasamos el molde y vertemos nuestra masa, 
                establecemos la temperatura del horno a 175º
                y lo dejamos durante una hora.
            </instruction>
            <instruction number="4">
                Una vez listo el bizcocho, dejamos enfriar 
                unos 10 minutos y desmoldamos.
            </instruction>
            <instruction number="5">
                Preparamos mousse de bienmesabe:
                semimontamos la nata junto, añadimos azúcar al gusto,
                vertemos la esencia de vainilla y mezclamos haciendo 
                movimientos envolventes con nuestro bienmesabe.
            </instruction>
            <instruction number="6">
                Nivelamos y cortamos el bizcocho con el mousse, 
                seguidamente añadimos un poco de dulce de leche 
                para dar un toque a caramelo.
            </instruction>
            <instruction number="7">
                Cubrimos y decoramos al gusto.
            </instruction>
        </instruction-list>

    </recipe>
    
    <recipe name="Judias pintas canarias" author="Carlos" duration="6000" difficulty="media" number-of-people="4" course="primero">
        
        <photo src="https://img-global.cpcdn.com/002_recipes/2d9430e2c813adec/640x640sq70/photo.jpg" alt="Imagen del resultado" />
        
        <ingredient-list>
            <ingredient name="Judías pintas" quantity="0.5" unit="kg" />
            <ingredient name="Pimiento verde" quantity="1" unit="unidad" />
            <ingredient name="Cebollas" quantity="2" unit="unidades" />
            <ingredient name="Chorizo de fabada" quantity="1" unit="unidad" />
            <ingredient name="Hoja de laurel seco" quantity="1" unit="unidad" />
            <ingredient name="Hoja de laurel verde" quantity="1" unit="unidad" />
            <ingredient name="Sal" quantity="2" unit="cucharadita" />
            <ingredient name="Aceite" quantity="10" unit="ml" />
        </ingredient-list>
        
        <instruction-list>
            <instruction number="1">
                Ponemos las judias de remojo en agua fría, durante 24 horas.
            </instruction>
            <instruction number="2">
                Si vemos que las judías absorben toda el agua y se quedan al
                descubierto, le añadimos mas, hasta que queden cubiertas de agua.
            </instruction>
            <instruction number="3">
                Después de hidratarlas durante 24 horas, las escurrimos bien y las lavamos.
            </instruction>
            <instruction number="4">
                Las ponemos en un caldero, le ponemos: 1 hoja de laurel seco, 1 cebolla mediana,
                un chorizo de fabada, las cubrimos de agua, le añadimos la sal y las ponemos a 
                guisar en un caldero durante 60 minutos. Siempre las vigilaremos por si se 
                consume mucho el agua, para añadirle más.
            </instruction>
            <instruction number="5">
                Cuando se hayan guisado, ponemos en otro caldero aceite y sofreímos la otra
                cebolla y el pimiento verde. Cuando el sofrito a punto de hacerse, sacamos
                el chorizo del caldero de las judías y lo picamos en tacos muy pequeños para
                añadirlo al sofrito, esperamos 1 minuto más y añadimos el sofrito a la judías.
                Dejamos cocinar a fuego medio durante 25 minutos más.
            </instruction>
            <instruction number="6">
                A la hora de servir este fabuloso plato, añadiremos la hoja de laurel fresco.
            </instruction>
        </instruction-list>
        
    </recipe>
    
    <recipe name="Papas con costillas" author="Daute" duration="5400" difficulty="media" number-of-people="4" course="segundo">
        
        <photo src="https://img-global.cpcdn.com/002_recipes/2541445_345997a7e2174209/640x640sq70/photo.jpg" alt="Imagen del resultado" />
        
        <ingredient-list>
            <ingredient name="Costillas de cerdo saladas" quantity="1" unit="kg" />
            <ingredient name="Papas" quantity="500" unit="gr" />
            <ingredient name="Piñas" quantity="3" unit="unidades" />
            <ingredient name="Manojo de cilantro" quantity="1" unit="unidad" />
            <ingredient name="Pimiento verde" quantity="0.5" unit="unidad" />
            <ingredient name="Comino en grano" quantity="1" unit="cucharadita" />
            <ingredient name="Sal gruesa" quantity="1" unit="cucharadita" />
            <ingredient name="Pimienta picona" quantity="0.5" unit="unidad" />
            <ingredient name="Dientes de ajo" quantity="5" unit="unidades" />
            <ingredient name="Vinagre blanco" quantity="2" unit="cucharadita" />
            <ingredient name="Aceite de oliva" quantity="4" unit="cucharadita" />
        </ingredient-list>
        
        <instruction-list>
            <instruction number="1">
                Poner las costillas en remojo durante varias horas e ir cambiando el
                agua.
            </instruction>
            <instruction number="2">
                Guisar las costillas durante 40 minutos en un caldero añadiendo un poco
                de sal y un trozo de limon. Si durante la coccción va subiendo grasa 
                habrá que espumarla. Mientras las costillas se guisan, se pueden ir
                pelando las papas y partiendo las piñas al gusto. Una vez hecho esto 
                habrá que dejarlas en una bandeja en agua.
            </instruction>
            <instruction number="3">
                Pasar por el tercer brazo los ajos picados, el pimiento verde cortado en trozos,
                la sal, el comino la pimienta picona y el manojo de cilantro lavado. Verter
                el vinagre blanco y medio vaso pequeño de agua. Cuando esté todo ligado, echar
                con cuidado el aceite y se bate unos minutos más, probando el nivel de sal.
            </instruction>
            <instruction number="4">
                Apartamos las costillas y ponemos a guisar las papas y la piña durante
                una media hora. No dejar que las papas se desmigajen.
            </instruction>
            <instruction number="5">
                Preparar el contenido del plato y verter por encima el mojo al gusto.
            </instruction>
        </instruction-list>
        
    </recipe>
    
    <recipe name="Carne compuesta" author="Carlos" duration="2400" difficulty="media" number-of-people="4" course="segundo">
        
        <photo src="http://casiopea.tac7.es/portalfedac/documentos/carne-con-papas.jpg" alt="Imagen del resultado" />
        
        <ingredient-list>
            <ingredient name="Carne de ternera en dados" quantity="1" unit="kg" />
            <ingredient name="Cebolla" quantity="1" unit="unidad" />
            <ingredient name="Tomate" quantity="1" unit="unidad" />
